#!/usr/bin/env bash
#
# A QA wizard walks a developer through every acceptance criterion of one
# feature, one stage at a time: open the page, do the steps, record pass or fail.
# Generated by /speckit.qa.walk from extensions/qa/scripts/qa-wizard.sh.
# Adapted from Matt Pocock's `wizard` skill (github.com/mattpocock/skills), MIT.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-check stages below the marker.
#
# Usage: ./qa-walk.sh [--only US1-2,EC-1] [--no-browser] [--reopen] [--results <path>]
#   --only       walk only these stage ids; other rows in the results file are kept
#   --no-browser print each URL instead of opening it
#   --reopen     open every URL again, even one already opened this run
#   --results    where the markdown results table goes (default: beside this script)

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

ONLY=""
NO_BROWSER="${NO_BROWSER:-}"
REOPEN=""
RESULTS=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    # A bare --only eats the next option as its value, so the filter matches no
    # stage and the walk reports success having checked nothing.
    --only)
      [[ $# -ge 2 && "$2" != --* ]] ||
        { printf '%s\n' '--only needs a stage list' >&2; exit 2; }
      ONLY="$2"; shift 2 ;;
    --only=*)     ONLY="${1#*=}"; shift ;;
    --no-browser) NO_BROWSER=1; shift ;;
    --reopen)     REOPEN=1; shift ;;
    --results)
      [[ $# -ge 2 && "$2" != --* ]] ||
        { printf '%s\n' '--results needs a path' >&2; exit 2; }
      RESULTS="$2"; shift 2 ;;
    --results=*)  RESULTS="${1#*=}"; shift ;;
    -h|--help)    sed -n '11,15p' "${BASH_SOURCE[0]}"; exit 0 ;;
    *) printf 'unknown option: %s\n' "$1" >&2; exit 2 ;;
  esac
done

# The last entry of BASH_SOURCE is the wizard itself, whether this library was
# copied into it or sourced from beside it, so the results land by the wizard.
_WIZARD="${BASH_SOURCE[$((${#BASH_SOURCE[@]} - 1))]}"
RESULTS="${RESULTS:-$(cd "$(dirname "$_WIZARD")" && pwd)/qa-walk-results.md}"

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
_STAGE_ID=""
_SKIPPING=""      # non-empty while --only excludes the current stage
RECORDS=()        # one tab-separated record per check: id, check, result, note
_SEEN=()          # every stage id this wizard declares, for the --only check
_OPENED=()        # every URL opened this run, so none is opened twice

# _clear wipes the terminal so only the current stage is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# _excluded ID succeeds when --only was given and does not name ID.
_excluded() {
  [[ -n "$ONLY" ]] || return 1
  [[ ",$ONLY," != *",$1,"* ]]
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser. This wizard tells you what to open and what to look\n' "$DIM"
  printf '  for, then records pass, fail or skip for each check. Stop any time with\n'
  printf '  Ctrl-C. Re-run with --only <id,...> to walk only the stages you name.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage ID "Title" clears the screen, announces the stage and shows progress.
# The id is the spec's own (US1-2, EC-1, SC-003) so results trace back to it.
stage() {
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  _STAGE_ID="$1"
  _SEEN+=("$1")
  if _excluded "$1"; then _SKIPPING=1; return 0; fi
  _SKIPPING=""
  _clear
  printf '\n%s%s▸ Stage %s/%s · %s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$2" "$RESET"
}

# say "..." prints the Given: the state the check starts from.
say()  { [[ -n "$_SKIPPING" ]] || printf '  %s\n' "$1"; }
# step "..." is one action the developer takes: the When.
step() { [[ -n "$_SKIPPING" ]] || printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { [[ -n "$_SKIPPING" ]] || printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { [[ -n "$_SKIPPING" ]] || printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }
good() { [[ -n "$_SKIPPING" ]] || printf '  %s✓%s %s\n' "$GREEN" "$RESET" "$1"; }

# open_url URL opens it in the developer's browser, cross-platform incl. WSL.
open_url() {
  [[ -n "$_SKIPPING" ]] && return 0
  local url="$1"
  if [[ -n "$NO_BROWSER" ]]; then
    printf '  %s↗ open%s %s\n' "$GREEN" "$RESET" "$url"; return 0
  fi
  # A walk returns to the same page many times: one wizard opens 5 pages across
  # 35 calls. Opening each time buries the reviewer in duplicate tabs, so a URL
  # already opened this run is named instead. --reopen restores every open.
  if [[ -z "$REOPEN" ]]; then
    local opened=" ${_OPENED[*]-} "
    if [[ "$opened" == *" $url "* ]]; then
      printf '  %s↗ already open%s %s\n' "$DIM" "$RESET" "$url"
      return 0
    fi
  fi
  _OPENED+=("$url")
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview      >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open     >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open         >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the developer to finish the manual part.
pause() {
  [[ -n "$_SKIPPING" ]] && return 0
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes. Put it before any
# step that changes data.
confirm() {
  [[ -n "$_SKIPPING" ]] && return 1
  local reply=""
  printf '  %s? %s [y/N]%s ' "$YELLOW" "$1" "$RESET"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# check "expected" states the Then and records pass, fail or skip for the
# current stage. A fail or a skip takes a one-line note.
check() {
  [[ -n "$_SKIPPING" ]] && return 0
  printf '  %s✔ Expected:%s %s\n' "$BOLD" "$RESET" "$1"
  local verdict="" reply="" note_text="" colour=""
  while [[ -z "$verdict" ]]; do
    printf '  %s? pass / fail / skip [p/f/s]%s ' "$YELLOW" "$RESET"
    # End of input records a skip, so a piped run never spins.
    if ! read -r reply; then verdict="skip"; break; fi
    case "${reply//[[:space:]]/}" in
      [pP]*) verdict="pass" ;;
      [fF]*) verdict="fail" ;;
      [sS]*) verdict="skip" ;;
    esac
  done
  if [[ "$verdict" != "pass" ]]; then
    printf '  %sNote (what you saw, or why skipped):%s ' "$BOLD" "$RESET"
    read -r note_text || true
  fi
  case "$verdict" in
    pass) colour="$GREEN" ;;
    fail) colour="$RED" ;;
    *)    colour="$YELLOW" ;;
  esac
  printf '  %s%s%s\n' "$colour" "$verdict" "$RESET"
  RECORDS+=("$(printf '%s\t%s\t%s\t%s' "$_STAGE_ID" "$1" "$verdict" "$note_text")")
}

# finish clears, writes the results table and shows the closing summary. On an
# --only run, rows for stages not walked this time are kept from the previous
# file. Exit code is 1 when any check failed.
finish() {
  local rows=() line id record r_id r_check r_result r_note
  local pass=0 fail=0 skip=0

  # An id that names no stage silently filters every stage out, and the walk
  # then reports success having checked nothing. Refuse before the results file
  # is written, so a mistyped id never overwrites the rows of a good run.
  if [[ -n "$ONLY" ]]; then
    # Join under the default IFS, because ${_SEEN[*]} separates on the first
    # character of IFS and the split below needs IFS to be a comma.
    local seen=" ${_SEEN[*]-} "
    local -a missing=()
    local want
    local IFS=,
    for want in $ONLY; do
      [[ "$seen" == *" $want "* ]] || missing+=("$want")
    done
    unset IFS
    if [[ ${#missing[@]} -gt 0 ]]; then
      printf '%s\n' "no stage in this wizard is named: ${missing[*]}" >&2
      exit 2
    fi
  fi

  if [[ -n "$ONLY" && -f "$RESULTS" ]]; then
    while IFS= read -r line; do
      [[ "$line" == '| '* ]] || continue
      id="${line#| }"; id="${id%% |*}"
      [[ "$id" == "Id" || "$id" == "---" ]] && continue
      _excluded "$id" && rows+=("$line")
    done < "$RESULTS"
  fi

  for record in ${RECORDS[@]+"${RECORDS[@]}"}; do
    IFS=$'\t' read -r r_id r_check r_result r_note <<< "$record"
    rows+=("| $r_id | ${r_check//|/\\|} | $r_result | ${r_note//|/\\|} |")
  done

  for line in ${rows[@]+"${rows[@]}"}; do
    case "$line" in
      *"| pass |"*) pass=$((pass + 1)) ;;
      *"| fail |"*) fail=$((fail + 1)) ;;
      *"| skip |"*) skip=$((skip + 1)) ;;
    esac
  done

  {
    printf '# QA walk results\n\n'
    printf -- '- **Run**: %s\n' "$(date '+%Y-%m-%d %H:%M')"
    printf -- '- **Result**: %s pass, %s fail, %s skip\n\n' "$pass" "$fail" "$skip"
    printf '| Id | Check | Result | Note |\n|---|---|---|---|\n'
    for line in ${rows[@]+"${rows[@]}"}; do printf '%s\n' "$line"; done
  } > "$RESULTS"

  _clear
  printf '\n'
  if [[ "$fail" -gt 0 ]]; then
    printf '%s%s  ✗ %s check(s) failed%s\n' "$BOLD" "$RED" "$fail" "$RESET"
  else
    printf '%s%s  ✓ Walk complete%s\n' "$BOLD" "$GREEN" "$RESET"
  fi
  printf '%s  %s pass, %s fail, %s skip · written to %s%s\n' \
    "$DIM" "$pass" "$fail" "$skip" "$RESULTS" "$RESET"
  for record in ${RECORDS[@]+"${RECORDS[@]}"}; do
    IFS=$'\t' read -r r_id r_check r_result r_note <<< "$record"
    [[ "$r_result" == "pass" ]] && continue
    printf '  %s- %s %s: %s%s\n' "$DIM" "$r_id" "$r_result" "$r_note" "$RESET"
  done
  printf '\n'
  [[ "$fail" -gt 0 ]] && exit 1
  return 0
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage per check, in the confirmed order.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=1

banner "QA walk: <feature name>"

# ── Example stage: replace with the real checks ───────────────────────────
stage "US1-1" "Sign-in lands on the dashboard"
say "Given a signed-out browser and the test account from the spec."
open_url "http://localhost:5000/account/login"
step "Enter the test account credentials and submit."
check "The browser lands on /dashboard and the header shows the account name."
# ──────────────────────────────────────────────────────────────────────────

finish
