#!/usr/bin/env pwsh
#
# A QA wizard walks a developer through every acceptance criterion of one
# feature, one stage at a time: open the page, do the steps, record pass or fail.
# Generated by /speckit.qa.walk from .specify/extensions/qa/scripts/qa-wizard.ps1.
# Adapted from Matt Pocock's `wizard` skill (github.com/mattpocock/skills), MIT.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-check stages below the marker.
#
# Usage: pwsh qa-walk.ps1 [-Only US1-2,EC-1] [-NoBrowser] [-Results <path>]
#   -Only       walk only these stage ids; other rows in the results file are kept
#   -NoBrowser  print each URL instead of opening it
#   -Results    where the markdown results table goes (default: beside this script)
param(
  [string[]]$Only = @(),
  [switch]$NoBrowser,
  [string]$Results = (Join-Path $PSScriptRoot 'qa-walk-results.md')
)
$ErrorActionPreference = 'Stop'

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

$script:Tty = -not [Console]::IsOutputRedirected
if ($script:Tty) {
  $BOLD = "`e[1m"; $DIM = "`e[2m"; $RESET = "`e[0m"
  $BLUE = "`e[34m"; $GREEN = "`e[32m"; $YELLOW = "`e[33m"; $RED = "`e[31m"
} else {
  $BOLD = ''; $DIM = ''; $RESET = ''; $BLUE = ''; $GREEN = ''; $YELLOW = ''; $RED = ''
}

# Author sets this at the top of the stages section.
$TotalStages = 0

$script:StageIndex = 0
$script:StageId = ''
$script:StageTitle = ''
$script:Skipping = $false   # true while -Only excludes the current stage
$script:Records = [System.Collections.Generic.List[object]]::new()

# Reads one line from stdin; $null at end of input, so a piped run never spins.
function Read-Line { [Console]::In.ReadLine() }

# Clear-Screen wipes the terminal so only the current stage is on screen.
# No-op when output is redirected, so piped logs stay readable.
function Clear-Screen { if ($script:Tty) { Clear-Host } }

# Banner "Title" shows the opening frame: what this wizard does.
function Banner([string]$Title) {
  Clear-Screen
  Write-Host ''
  Write-Host "$BOLD$BLUE  $Title$RESET"
  Write-Host "$DIM  $TotalStages stages$RESET"
  Write-Host ''
  Write-Host "$DIM  You drive the browser. This wizard tells you what to open and what to look"
  Write-Host "  for, then records pass, fail or skip for each check. Stop any time with"
  Write-Host "  Ctrl-C. Re-run with -Only <id,...> to walk only the stages you name.$RESET"
  Pause 'Ready to start?'
}

# Stage "Id" "Title" clears the screen, announces the stage and shows progress.
# The id is the spec's own (US1-2, EC-1, SC-003) so results trace back to it.
function Stage([string]$Id, [string]$Title) {
  $script:StageIndex++
  $script:StageId = $Id
  $script:StageTitle = $Title
  $script:Skipping = ($Only.Count -gt 0) -and ($Id -notin $Only)
  if ($script:Skipping) { return }
  Clear-Screen
  Write-Host ''
  Write-Host "$BOLD$BLUE▸ Stage $script:StageIndex/$TotalStages · $Id · $Title$RESET"
}

# Say "..." prints a plain line: the Given, the state the check starts from.
function Say([string]$Text)  { if (-not $script:Skipping) { Write-Host "  $Text" } }
# Step "..." is one action the developer takes: the When.
function Step([string]$Text) { if (-not $script:Skipping) { Write-Host "  $BLUE•$RESET $Text" } }
function Note([string]$Text) { if (-not $script:Skipping) { Write-Host "  $DIM$Text$RESET" } }
function Warn([string]$Text) { if (-not $script:Skipping) { Write-Host "  $YELLOW⚠ $Text$RESET" } }

# Open-Url URL opens it in the developer's browser on macOS, Windows and Linux.
function Open-Url([string]$Url) {
  if ($script:Skipping) { return }
  if ($NoBrowser) { Write-Host "  $GREEN↗ open$RESET $Url"; return }
  Write-Host "  $GREEN↗ opening$RESET $Url"
  try { Start-Process $Url } catch { Warn "could not open a browser; visit it manually: $Url" }
}

# Pause "msg" waits for the developer to finish the manual part.
function Pause([string]$Message = 'Press Enter to continue') {
  if ($script:Skipping) { return }
  Write-Host -NoNewline "  $DIM$Message$RESET "
  $null = Read-Line
}

# Confirm "question" is a y/N gate; returns $true on yes. Put it before any
# step that changes data.
function Confirm([string]$Question) {
  if ($script:Skipping) { return $false }
  Write-Host -NoNewline "  ${YELLOW}? $Question [y/N]$RESET "
  $reply = Read-Line
  return [bool]($reply -match '^[Yy]')
}

# Check "expected" states the Then and records pass, fail or skip for the
# current stage. A fail or a skip takes a one-line note.
function Check([string]$Expected) {
  if ($script:Skipping) { return }
  Write-Host "  $BOLD✔ Expected:$RESET $Expected"
  $verdict = $null
  while (-not $verdict) {
    Write-Host -NoNewline "  ${YELLOW}? pass / fail / skip [p/f/s]$RESET "
    $reply = Read-Line
    if ($null -eq $reply) { $verdict = 'skip'; break }   # end of input
    switch -Regex ($reply.Trim()) {
      '^[pP]' { $verdict = 'pass' }
      '^[fF]' { $verdict = 'fail' }
      '^[sS]' { $verdict = 'skip' }
    }
  }
  $note = ''
  if ($verdict -ne 'pass') {
    Write-Host -NoNewline "  ${BOLD}Note (what you saw, or why skipped):$RESET "
    $note = [string](Read-Line)
  }
  $colour = switch ($verdict) { 'pass' { $GREEN } 'fail' { $RED } default { $YELLOW } }
  Write-Host "  $colour$verdict$RESET"
  $script:Records.Add([pscustomobject]@{
    Id = $script:StageId; Check = $Expected; Result = $verdict; Note = $note.Trim()
  })
}

# Finish shows the closing summary and writes the results table. On a -Only
# run, rows for stages not walked this time are kept from the previous file.
# Exit code is 1 when any check failed.
function Finish {
  $rows = [System.Collections.Generic.List[string]]::new()
  if ($Only.Count -gt 0 -and (Test-Path $Results)) {
    foreach ($line in Get-Content $Results) {
      if ($line -match '^\| (?<id>[^|]+?) \|' -and $Matches.id -notin $Only -and $Matches.id -notin @('Id', '---')) {
        $rows.Add($line)
      }
    }
  }
  foreach ($r in $script:Records) {
    $cell = { param($s) ($s -replace '\|', '\|') }
    $rows.Add("| $($r.Id) | $(& $cell $r.Check) | $($r.Result) | $(& $cell $r.Note) |")
  }
  $all = foreach ($row in $rows) { ($row -split '\|')[3].Trim() }
  $pass = @($all | Where-Object { $_ -eq 'pass' }).Count
  $fail = @($all | Where-Object { $_ -eq 'fail' }).Count
  $skip = @($all | Where-Object { $_ -eq 'skip' }).Count

  $md = @(
    '# QA walk results'
    ''
    "- **Run**: $(Get-Date -Format 'yyyy-MM-dd HH:mm')"
    "- **Result**: $pass pass, $fail fail, $skip skip"
    ''
    '| Id | Check | Result | Note |'
    '|---|---|---|---|'
  ) + $rows
  [System.IO.File]::WriteAllLines($Results, [string[]]$md)

  Clear-Screen
  Write-Host ''
  $head = if ($fail) { "$RED  ✗ $fail check(s) failed" } else { "$GREEN  ✓ Walk complete" }
  Write-Host "$BOLD$head$RESET"
  Write-Host "$DIM  $pass pass, $fail fail, $skip skip · written to $Results$RESET"
  foreach ($r in $script:Records | Where-Object Result -ne 'pass') {
    Write-Host "  $DIM- $($r.Id) $($r.Result): $($r.Note)$RESET"
  }
  Write-Host ''
  if ($fail) { exit 1 }
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One Stage per check, in the confirmed order.
# Replace the example below. Set $TotalStages to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

$TotalStages = 1

Banner 'QA walk: <feature name>'

# ── Example stage: replace with the real checks ───────────────────────────
Stage 'US1-1' 'Sign-in lands on the dashboard'
Say 'Given a signed-out browser and the test account from the spec.'
Open-Url 'http://localhost:5000/account/login'
Step 'Enter the test account credentials and submit.'
Check 'The browser lands on /dashboard and the header shows the account name.'
# ──────────────────────────────────────────────────────────────────────────

Finish
