// <auto-generated />
using System;
using KCC.Contributions.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KCC.Contributions.Data.Migrations
{
    [DbContext(typeof(ContributionsDbContext))]
    [Migration("20260925124912_InitialContributions")]
    partial class InitialContributions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("KCC.Contributions.Data.CookNote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT")
                        .HasColumnName("created");

                    b.Property<Guid>("MemberKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("memberKey");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("text");

                    b.Property<Guid>("VariantKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("variantKey");

                    b.HasKey("Id");

                    b.HasIndex("VariantKey");

                    b.ToTable("kccCookNote", (string)null);
                });

            modelBuilder.Entity("KCC.Contributions.Data.CookedMark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT")
                        .HasColumnName("created");

                    b.Property<Guid>("MemberKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("memberKey");

                    b.Property<Guid>("VariantKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("variantKey");

                    b.HasKey("Id");

                    b.HasIndex("VariantKey", "MemberKey")
                        .IsUnique();

                    b.ToTable("kccCookedMark", (string)null);
                });

            modelBuilder.Entity("KCC.Contributions.Data.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created")
                        .HasColumnType("TEXT")
                        .HasColumnName("created");

                    b.Property<Guid>("MemberKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("memberKey");

                    b.Property<DateTime>("Modified")
                        .HasColumnType("TEXT")
                        .HasColumnName("modified");

                    b.Property<double>("Rating")
                        .HasColumnType("REAL")
                        .HasColumnName("rating");

                    b.Property<string>("Text")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("text");

                    b.Property<Guid>("VariantKey")
                        .HasColumnType("TEXT")
                        .HasColumnName("variantKey");

                    b.HasKey("Id");

                    b.HasIndex("VariantKey", "MemberKey")
                        .IsUnique();

                    b.ToTable("kccReview", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
