/**
 * Tailwind background color class strings
 */
export type BackgroundColor =
  | 'bg-surface-200'
  | 'bg-surface-300'
  | 'bg-surface-400'
  | 'bg-surface-500'
  | 'bg-surface-600'
  | 'bg-surface-700'
  | 'bg-rosewater'
  | 'bg-flamingo'
  | 'bg-pink'
  | 'bg-mauve'
  | 'bg-red'
  | 'bg-maroon'
  | 'bg-peach'
  | 'bg-yellow'
  | 'bg-green'
  | 'bg-teal'
  | 'bg-sky'
  | 'bg-sapphire'
  | 'bg-blue'
  | 'bg-lavender'
  | 'bg-bone'
  | 'bg-bone-dark'
  | 'bg-onyx'
  | 'bg-onyx-light'

/**
 * Tailwind text color class strings
 */
export type TextColor =
  | 'text-surface-200'
  | 'text-surface-300'
  | 'text-surface-400'
  | 'text-surface-500'
  | 'text-surface-600'
  | 'text-surface-700'
  | 'text-overlay-200'
  | 'text-overlay-300'
  | 'text-overlay-400'
  | 'text-rosewater'
  | 'text-flamingo'
  | 'text-pink'
  | 'text-mauve'
  | 'text-red'
  | 'text-maroon'
  | 'text-peach'
  | 'text-yellow'
  | 'text-green'
  | 'text-teal'
  | 'text-sky'
  | 'text-sapphire'
  | 'text-blue'
  | 'text-lavender'
  | 'text-bone'
  | 'text-bone-dark'
  | 'text-onyx'
  | 'text-onyx-light'
  | 'text-text'
  | 'text-subtext-300'
  | 'text-subtext-400'
