/**
 * Tailwind background color class strings
 */
export type BackgroundColor =
  | 'bg-base'
  | 'bg-mantle'
  | 'bg-crust'
  | 'bg-surface'
  | 'bg-surface-100'
  | 'bg-surface-200'
  | 'bg-rosewater'
  | 'bg-flamingo'
  | 'bg-pink'
  | 'bg-mauve'
  | 'bg-red'
  | 'bg-maroon'
  | 'bg-peach'
  | 'bg-yellow'
  | 'bg-green'
  | 'bg-teal'
  | 'bg-sky'
  | 'bg-sapphire'
  | 'bg-blue'
  | 'bg-lavender'
  | 'bg-bone'
  | 'bg-bone-dark'
  | 'bg-onyx'
  | 'bg-onyx-light'

/**
 * Tailwind text color class strings
 */
export type TextColor =
  | 'text-base'
  | 'text-mantle'
  | 'text-crust'
  | 'text-surface'
  | 'text-surface-100'
  | 'text-surface-200'
  | 'text-rosewater'
  | 'text-flamingo'
  | 'text-pink'
  | 'text-mauve'
  | 'text-red'
  | 'text-maroon'
  | 'text-peach'
  | 'text-yellow'
  | 'text-green'
  | 'text-teal'
  | 'text-sky'
  | 'text-sapphire'
  | 'text-blue'
  | 'text-lavender'
  | 'text-bone'
  | 'text-bone-dark'
  | 'text-onyx'
  | 'text-onyx-light'
  | 'text-text'
  | 'text-subtext'
  | 'text-subtext-100'
