namespace KCC.Admin;

/// <summary>
/// The curated set of Font Awesome Pro duotone icons available for recipes, as full
/// Font Awesome class strings (e.g. "fa-duotone fa-solid fa-cheese"). This is the single
/// source of truth shared by the AI enum, the deterministic fallback, and the admin
/// icon-selector form component; the value is stored verbatim and rendered as-is.
/// </summary>
public static class RecipeIcons
{
    public static readonly IReadOnlyList<string> All =
    [
        "fa-duotone fa-aeropress",
        "fa-duotone fa-apple-whole",
        "fa-duotone fa-bacon",
        "fa-duotone fa-bagel",
        "fa-duotone fa-baguette",
        "fa-duotone fa-beer-mug",
        "fa-duotone fa-beer-mug-empty",
        "fa-duotone fa-blender",
        "fa-duotone fa-bone",
        "fa-duotone fa-bottle-baby",
        "fa-duotone fa-bottle-droplet",
        "fa-duotone fa-bottle-water",
        "fa-duotone fa-bowl-chopsticks",
        "fa-duotone fa-bowl-chopsticks-noodles",
        "fa-duotone fa-bowl-food",
        "fa-duotone fa-bowl-hot",
        "fa-duotone fa-bowl-rice",
        "fa-duotone fa-bowl-scoop",
        "fa-duotone fa-bowl-scoops",
        "fa-duotone fa-bowl-soft-serve",
        "fa-duotone fa-bowl-spoon",
        "fa-duotone fa-bread-loaf",
        "fa-duotone fa-bread-slice",
        "fa-duotone fa-bread-slice-butter",
        "fa-duotone fa-burger",
        "fa-duotone fa-burger-cheese",
        "fa-duotone fa-burger-fries",
        "fa-duotone fa-burger-glass",
        "fa-duotone fa-burger-lettuce",
        "fa-duotone fa-burger-soda",
        "fa-duotone fa-burrito",
        "fa-duotone fa-butter",
        "fa-duotone fa-cake-candles",
        "fa-duotone fa-cake-slice",
        "fa-duotone fa-can-food",
        "fa-duotone fa-candy",
        "fa-duotone fa-candy-bar",
        "fa-duotone fa-candy-cane",
        "fa-duotone fa-candy-corn",
        "fa-duotone fa-carrot",
        "fa-duotone fa-champagne-glass",
        "fa-duotone fa-champagne-glasses",
        "fa-duotone fa-cheese",
        "fa-duotone fa-cheese-swiss",
        "fa-duotone fa-chemex",
        "fa-duotone fa-chopsticks",
        "fa-duotone fa-circle-gf",
        "fa-duotone fa-cloud-meatball",
        "fa-duotone fa-coffee-bean",
        "fa-duotone fa-coffee-beans",
        "fa-duotone fa-coffee-pot",
        "fa-duotone fa-cookie",
        "fa-duotone fa-corn",
        "fa-duotone fa-crab",
        "fa-duotone fa-crate-apple",
        "fa-duotone fa-croissant",
        "fa-duotone fa-cubes-stacked",
        "fa-duotone fa-cup-straw",
        "fa-duotone fa-cup-straw-swoosh",
        "fa-duotone fa-cup-togo",
        "fa-duotone fa-cupcake",
        "fa-duotone fa-custard",
        "fa-duotone fa-donut",
        "fa-duotone fa-drumstick",
        "fa-duotone fa-drumstick-bite",
        "fa-duotone fa-egg",
        "fa-duotone fa-egg-fried",
        "fa-duotone fa-falafel",
        "fa-duotone fa-fish",
        "fa-duotone fa-fish-bones",
        "fa-duotone fa-fish-cooked",
        "fa-duotone fa-fish-fins",
        "fa-duotone fa-flask",
        "fa-duotone fa-flask-round-poison",
        "fa-duotone fa-flask-round-potion",
        "fa-duotone fa-flatbread",
        "fa-duotone fa-flatbread-stuffed",
        "fa-duotone fa-fondue-pot",
        "fa-duotone fa-french-fries",
        "fa-duotone fa-gingerbread-man",
        "fa-duotone fa-glass",
        "fa-duotone fa-glass-citrus",
        "fa-duotone fa-glass-empty",
        "fa-duotone fa-glass-half",
        "fa-duotone fa-glass-water",
        "fa-duotone fa-glass-water-droplet",
        "fa-duotone fa-hat-chef",
        "fa-duotone fa-honey-pot",
        "fa-duotone fa-hotdog",
        "fa-duotone fa-ice-cream",
        "fa-duotone fa-jar",
        "fa-duotone fa-jar-wheat",
        "fa-duotone fa-jug",
        "fa-duotone fa-jug-bottle",
        "fa-duotone fa-lemon",
        "fa-duotone fa-lobster",
        "fa-duotone fa-lollipop",
        "fa-duotone fa-lychee",
        "fa-duotone fa-martini-glass",
        "fa-duotone fa-martini-glass-citrus",
        "fa-duotone fa-martini-glass-empty",
        "fa-duotone fa-meat",
        "fa-duotone fa-mug",
        "fa-duotone fa-mug-hot",
        "fa-duotone fa-mug-marshmallows",
        "fa-duotone fa-mug-saucer",
        "fa-duotone fa-mug-tea",
        "fa-duotone fa-mug-tea-saucer",
        "fa-duotone fa-pan-food",
        "fa-duotone fa-pan-frying",
        "fa-duotone fa-pancakes",
        "fa-duotone fa-pepper-hot",
        "fa-duotone fa-pie",
        "fa-duotone fa-pizza",
        "fa-duotone fa-pizza-slice",
        "fa-duotone fa-plate-wheat",
        "fa-duotone fa-popcorn",
        "fa-duotone fa-popsicle",
        "fa-duotone fa-pot-food",
        "fa-duotone fa-pretzel",
        "fa-duotone fa-pumpkin",
        "fa-duotone fa-salad",
        "fa-duotone fa-salt-shaker",
        "fa-duotone fa-sandwich",
        "fa-duotone fa-sausage",
        "fa-duotone fa-seedling",
        "fa-duotone fa-shish-kebab",
        "fa-duotone fa-shrimp",
        "fa-duotone fa-soft-serve",
        "fa-duotone fa-squid",
        "fa-duotone fa-steak",
        "fa-duotone fa-stroopwafel",
        "fa-duotone fa-sushi",
        "fa-duotone fa-sushi-roll",
        "fa-duotone fa-table-bar",
        "fa-duotone fa-table-dining",
        "fa-duotone fa-taco",
        "fa-duotone fa-tamale",
        "fa-duotone fa-truck-utensils",
        "fa-duotone fa-turkey",
        "fa-duotone fa-user-chef",
        "fa-duotone fa-user-chef-hair-long",
        "fa-duotone fa-waffle",
        "fa-duotone fa-wheat",
        "fa-duotone fa-wheat-awn",
        "fa-duotone fa-wheat-awn-circle-exclamation",
        "fa-duotone fa-wheat-awn-slash",
        "fa-duotone fa-wheat-slash",
        "fa-duotone fa-whiskey-glass",
        "fa-duotone fa-whiskey-glass-ice",
        "fa-duotone fa-wine-bottle",
        "fa-duotone fa-wine-glass",
        "fa-duotone fa-wine-glass-empty",
    ];

    /// <summary>
    /// Deterministically maps a seed (e.g. the recipe name) to one icon. Stable across calls,
    /// so a recipe always gets the same fallback icon and never an empty value.
    /// </summary>
    /// <param name="seed">The seed value, typically the recipe name.</param>
    /// <returns>A full Font Awesome class string from <see cref="All"/>.</returns>
    public static string Fallback(string seed)
    {
        int hash = 0;
        foreach (char c in seed ?? string.Empty)
        {
            hash = unchecked((hash * 31) + c);
        }

        int index = Math.Abs(hash % All.Count);
        return All[index];
    }

    public static bool IsKnown(string icon) => icon is not null && All.Contains(icon);
}
