import { tornPolygon, type Corner } from './tornPolygon.ts'

export interface TearPreset {
  /** Custom-property and class suffix: `--tear-1`, `.kcc-tear-1`. */
  name: string
  seed: number
  amp: number
  chamfer: number
  corner: Corner
  pointsPerSide: number
  /** Slip tilt in degrees, written to `--r`. Tiles tilt through `.kcc-tilewrap` instead. */
  tilt?: number
}

// Seeds come from the mockup's own seed → cut / rot tables so the six standard sheets mix corners and tilts,
// with one uncut sheet (about one in four, per the identity). The hero takes the detail page's seed.
export const SHEET_TEARS: TearPreset[] = [
  { name: 'tear-1', seed: 312, amp: 2.4, chamfer: 19, corner: 1, pointsPerSide: 80, tilt: 0.3 },
  { name: 'tear-2', seed: 20, amp: 2.4, chamfer: 17, corner: 2, pointsPerSide: 80, tilt: -0.98 },
  { name: 'tear-3', seed: 33, amp: 2.4, chamfer: 0, corner: 1, pointsPerSide: 80, tilt: 0.05 },
  { name: 'tear-4', seed: 101, amp: 2.4, chamfer: 18, corner: 3, pointsPerSide: 80, tilt: -0.52 },
  { name: 'tear-5', seed: 266, amp: 2.4, chamfer: 20, corner: 2, pointsPerSide: 80, tilt: 0.63 },
  { name: 'tear-6', seed: 149, amp: 2.4, chamfer: 17, corner: 3, pointsPerSide: 80, tilt: -0.7 },
  { name: 'tear-hero', seed: 301, amp: 2.4, chamfer: 28, corner: 1, pointsPerSide: 160, tilt: -0.58 },
]

export const TILE_TEARS: TearPreset[] = [
  { name: 'tear-tile-1', seed: 9, amp: 1.8, chamfer: 0, corner: 1, pointsPerSide: 24 },
  { name: 'tear-tile-2', seed: 28, amp: 1.8, chamfer: 0, corner: 1, pointsPerSide: 24 },
  { name: 'tear-tile-3', seed: 47, amp: 1.8, chamfer: 0, corner: 1, pointsPerSide: 24 },
]

const declaration = (p: TearPreset) => `  --${p.name}: ${tornPolygon(p)};`
const sheetClass = (p: TearPreset) => `  .kcc-${p.name} {\n    --tear: var(--${p.name});\n    --r: ${p.tilt ?? 0};\n  }`
const tileClass = (p: TearPreset) => `  .kcc-${p.name} {\n    --tear: var(--${p.name});\n  }`

/** The whole of Styles/Torn/Tears.css. */
export function tearsCss(): string {
  return [
    '/* GENERATED by `yarn tears` from Features/Torn/tears.ts. Do not edit: tears.test.ts diffs this file against the generator. */',
    ':root {',
    ...[...SHEET_TEARS, ...TILE_TEARS].map(declaration),
    '}',
    '',
    '@layer components {',
    ...SHEET_TEARS.map(sheetClass),
    ...TILE_TEARS.map(tileClass),
    '}',
    '',
  ].join('\n')
}
