namespace KCC.Web.Features.DevTools.RecipeSeed;

// Pure, framework-free description of the test-data set the seeder materializes into published
// KCC.Recipe / KCC.RecipeVariant web pages plus VariantReview rows. Kept separate from the seeding
// logic so the dataset reads as a coverage matrix (see RecipeSeedData) rather than Kentico plumbing.

/// <summary>One ingredient line. Only <see cref="Name"/> is indexed for free-text search.</summary>
public sealed record SeedIngredient(string Name, decimal? Quantity, string Unit, bool IsEyeballed = false);

/// <summary>One numbered instruction step. Instruction text is intentionally NOT indexed.</summary>
public sealed record SeedInstruction(int Step, string Text);

/// <summary>
/// A recipe variant. Its <see cref="PrepMinutes"/> + <see cref="CookMinutes"/> feed the recipe's
/// indexed FastestTime (the minimum total across its variants), and its <see cref="Diets"/> tags feed
/// the multi-valued diet facet (the union across all of a recipe's variants).
/// </summary>
public sealed record SeedVariant(
    string Name,
    string Description,
    int PrepMinutes,
    int CookMinutes,
    int Servings,
    string Icon,
    string[] Diets,
    SeedIngredient[] Ingredients,
    SeedInstruction[] Instructions);

/// <summary>A single review's star rating (0.5–5 in half-star steps); text is generated by the seeder.</summary>
public sealed record SeedReview(decimal Rating);

/// <summary>
/// A recipe and everything the search index derives from it. <see cref="Reviews"/> are attached to the
/// first variant (the recipe-level average the index stores aggregates every review by recipe GUID).
/// </summary>
public sealed record SeedRecipe(
    string Name,
    string Category,
    string AuthorKey,
    string Description,
    string Icon,
    int PublishedDaysAgo,
    SeedVariant[] Variants,
    SeedReview[] Reviews);

/// <summary>A distinctively-named author member, so the recipe's searchable "started by" name is assertable.</summary>
public sealed record SeedAuthor(string Key, string UserName, string Email, string FirstName, string LastName);
